apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: {{ .Values.postgres.auth.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgres.auth.password | b64enc | quote }}